name: tezda
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.2.0
  get_storage: ^2.1.1
  http_parser: ^4.0.2
  lottie: ^3.1.2

  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
